- implement softmax

In [18]:
import numpy as np
from numpy import linalg as LA

## Sigmoid

In [7]:
def sigmoid(x):
    return 1./(1+np.exp(-x))

In [8]:
x = np.array([1, 2, 3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

## Reshape

In [14]:
A = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ],
        [                
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ]
    ])
A.shape

(2, 3, 3)

In [17]:
A.reshape(A.shape[0]*A.shape[1]*A.shape[2], 1).shape

(18, 1)

## Normalize rows

In [41]:
def normalizeRows(x):
    norm = LA.norm(x, axis=1, keepdims = True)
    return x / norm

In [42]:
x = np.array(
    [
        [0, 3, 4],
        [1, 6, 4]
    ]
)

normalizeRows(x)

[[5.        ]
 [7.28010989]]


array([[0.        , 0.6       , 0.8       ],
       [0.13736056, 0.82416338, 0.54944226]])

## Softmax

In [45]:
def softmax(x):
    A = np.exp(x)
    r = np.sum(A, axis=1, keepdims = True)
    return A / r

In [46]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])

softmax(x)

array([[9.80897665e-01, 8.94462891e-04, 1.79657674e-02, 1.21052389e-04,
        1.21052389e-04],
       [8.78679856e-01, 1.18916387e-01, 8.01252314e-04, 8.01252314e-04,
        8.01252314e-04]])